name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Build and test
        working-directory: rentalservice
        run: |
          export SHELL=/bin/bash
          ./gradlew build
      - name: Docker images
        working-directory: rentalservice
        run: |
          export SHELL=/bin/bash
          docker build -t rentalservice .
          docker run -p 4000:8080 rentalservice
          curl http://127.0.0.1:4000/cars

